version: "3"
services:
  redis:
    image: redis:alpine

  web_1:
    build: ./coolsite/
    container_name: web_1
    command: gunicorn coolsite.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - redis

  web_2:
    build: ./coolsite/
    container_name: web_2
    command: gunicorn coolsite.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - redis

  nginx:
    image: nginx:1.22.0-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web_1
      - web_2

  #   volumes:
  #     - .:/code
  #   env_file:
  #     - .env.dev
  #   depends_on:
  #     - db
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: db_name
  #     POSTGRES_USER: db_user
  #     POSTGRES_PASSWORD: db_password
